[package]
name = "merge"
version = "0.1.0"
edition = "2024"

[dependencies]
language = { path = "../language" }
tree-sitter = "0.25.8"
tree-sitter-c = "0.24.1"

[dependencies.uuid]
version = "1.17.0"
# Lets you generate random UUIDs
features = ["v4", "serde"]